[general]
import = [
  "~/.config/alacritty/catppuccin-frappe.toml"
]
live_config_reload = true

[window]
opacity = 0.85
dimensions = { columns = 120, lines = 35 }
position = { x = 650, y = 300 }

[font]
normal = { family = "FiraCode Nerd Font Mono", style="Regular" }
size = 14

[selection]
save_to_clipboard = true

[cursor]
style = { blinking = "Always" }
blink_interval = 600
blink_timeout = 0

[mouse]
hide_when_typing = true

